### Variables de configuracion de entorno de Emprender

###=============================================================================
### Dominio (requerido)
###=============================================================================
EMPRENDER_DOMINIO: "localhost"
EMPRENDER_MAIL: "emprender@hamekoz.com.ar"

###=============================================================================
### Google Analytics (opcional)
###=============================================================================
#EMPRENDER_GOOGLE_ANALYTICS_ID: ""

###=============================================================================
### Envio de corro electronico
###=============================================================================
### Opcional para implementacion local
### Obligato para implementacion heroku
#EMPRENDER_MAIL_SMTP: "enable"
#EMPRENDER_MAIL_SERVIDOR: ""
#EMPRENDER_MAIL_PUERTO: ""
#EMPRENDER_MAIL_DOMINIO: ""
#EMPRENDER_MAIL_USUARIO: ""
#EMPRENDER_MAIL_PASSWORD: ""

###=============================================================================
### Base de datos
###=============================================================================
### Obligatorio para implementacion local
### No requerido para implementacion heroku
#EMPRENDER_DB_DABABASE: "emprender"
#EMPRENDER_DB_USUARIO: "root"
#EMPRENDER_DB_PASSWORD: ""
#EMPRENDER_DB_SOCKET: "/var/lib/mysql/mysql.sock"

###=============================================================================
### Dropbox
###=============================================================================
### Opcional para implementacion local
### Obligato para implementacion heroku
#EMPRENDER_DROPBOX: "enable"
#EMPRENDER_DROPBOX_APP_KEY: ""
#EMPRENDER_DROPBOX_APP_SECRET: ""
#EMPRENDER_DROPBOX_ACCESS_TOKEN: ""
#EMPRENDER_DROPBOX_ACCESS_TOKEN_SECRET: ""
#EMPRENDER_DROPBOX_USER_ID: ""
#EMPRENDER_DROPBOX_ACCESS_TYPE: "dropbox"
