app_key: <%= Figaro.env.emprender_dropbox_app_key %>
app_secret: <%= Figaro.env.emprender_dropbox_app_secret %>
access_token: <%= Figaro.env.emprender_dropbox_access_token %>
access_token_secret: <%= Figaro.env.emprender_dropbox_access_token_secret %>
user_id: <%= Figaro.env.emprender_dropbox_user_id %>
access_type: <%= Figaro.env.emprender_dropbox_access_type %>
