Barrio.create :nombre => "9 de julio"
Barrio.create :nombre => "Aeropuerto"
Barrio.create :nombre => "Aeroparque"
Barrio.create :nombre => "Alfar"
Barrio.create :nombre => "Ameghino"
Barrio.create :nombre => "Antartida Argentina"
Barrio.create :nombre => "Barrio 180"
Barrio.create :nombre => "Batan"
Barrio.create :nombre => "Bernardino Rivadavia"
Barrio.create :nombre => "Belgrano"
Barrio.create :nombre => "Belisario Roldan"
Barrio.create :nombre => "Bosque Alegre"
Barrio.create :nombre => "Bosque Peralta Ramos"
Barrio.create :nombre => "Caisamar"
Barrio.create :nombre => "Cerrito"
Barrio.create :nombre => "Cerrito Sur"
Barrio.create :nombre => "Cerrito San Salvador"
Barrio.create :nombre => "Colina Alegre"
Barrio.create :nombre => "Constitucion"
Barrio.create :nombre => "Coronel Dorrego"
Barrio.create :nombre => "Costa Azul"
Barrio.create :nombre => "Don Bosco"
Barrio.create :nombre => "Don Emilio"
Barrio.create :nombre => "Dorrego"
Barrio.create :nombre => "El Grosellar"
Barrio.create :nombre => "El Martillo"
Barrio.create :nombre => "El Progreso"
Barrio.create :nombre => "Estrada"
Barrio.create :nombre => "Faro"
Barrio.create :nombre => "J. Lopez de Gomara"
Barrio.create :nombre => "Juramento"
Barrio.create :nombre => "Las Avenidas"
Barrio.create :nombre => "Las Colinas de Peralta Ramos"
Barrio.create :nombre => "La Florida"
Barrio.create :nombre => "La Perla"
Barrio.create :nombre => "La Zulema"
Barrio.create :nombre => "Libertad"
Barrio.create :nombre => "Los Acantilados"
Barrio.create :nombre => "Los Pinares"
Barrio.create :nombre => "Los Tilos"
Barrio.create :nombre => "Los Troncos"
Barrio.create :nombre => "Lourdes"
Barrio.create :nombre => "Malvinas Argentinas"
Barrio.create :nombre => "Mar y Sol"
Barrio.create :nombre => "Newbery"
Barrio.create :nombre => "Nueva Pompeya"
Barrio.create :nombre => "Montemar"
Barrio.create :nombre => "Parque Hermoso"
Barrio.create :nombre => "Parque La Florida"
Barrio.create :nombre => "Parque Luro"
Barrio.create :nombre => "Parque Palermo"
Barrio.create :nombre => "Parque Pena"
Barrio.create :nombre => "Peralta Ramos Oeste"
Barrio.create :nombre => "Pinos de Anchorena"
Barrio.create :nombre => "Playa Chapadmalal"
Barrio.create :nombre => "Playa Grande"
Barrio.create :nombre => "Playa Los Lobos"
Barrio.create :nombre => "Playa Serena"
Barrio.create :nombre => "Primera Junta"
Barrio.create :nombre => "Punta Mogotes"
Barrio.create :nombre => "San Antonio"
Barrio.create :nombre => "San Carlos"
Barrio.create :nombre => "San Eduardo"
Barrio.create :nombre => "San Geronimo"
Barrio.create :nombre => "San Jacinto"
Barrio.create :nombre => "San Jose"
Barrio.create :nombre => "San Juan"
Barrio.create :nombre => "San Martin"
Barrio.create :nombre => "San Patricio"
Barrio.create :nombre => "San Salvador"
Barrio.create :nombre => "Santa Monica"
Barrio.create :nombre => "Santa Rita"
Barrio.create :nombre => "Santa Rosa de Lima"
Barrio.create :nombre => "Santa Rosa del Mar"
Barrio.create :nombre => "Sarmiento"
Barrio.create :nombre => "Stella Maris"
Barrio.create :nombre => "Termas Huinco"
Barrio.create :nombre => "Villa Primera"
Barrio.create :nombre => "Zacagnini"

Rubro.create :nombre => "Artesanias"
Rubro.create :nombre => "Bazar"
Rubro.create :nombre => "Hogar"
Rubro.create :nombre => "Decoracion"
Rubro.create :nombre => "Entretenimiento"
Rubro.create :nombre => "Juguetes"
Rubro.create :nombre => "Gastronomia"
Rubro.create :nombre => "Alimentos y bebidas"
Rubro.create :nombre => "Grafica / Imprenta"
Rubro.create :nombre => "Informatica"
Rubro.create :nombre => "Electronica"
Rubro.create :nombre => "Textil: bebes y ninos"
Rubro.create :nombre => "Textil: adultos"
Rubro.create :nombre => "Textil: varios"
Rubro.create :nombre => "Salud y belleza"
Rubro.create :nombre => "Servicios"

Clasificacion.create :codigo => "1112", :nombre => "Cultivo de cereales forrajeros"
Clasificacion.create :codigo => "1113", :nombre => "Cultivo de oleaginosas excepto el de semillas para siembra"
Clasificacion.create :codigo => "1114", :nombre => "Cultivo de pastos forrajeros"
Clasificacion.create :codigo => "1121", :nombre => "Cultivo de papa, batata y mandioca"
Clasificacion.create :codigo => "1122", :nombre => "Cultivo de bulbos, brotes, raices y hortalizas de fruto"
Clasificacion.create :codigo => "1123", :nombre => "Cultivo de hortalizas de hoja y de otras hortalizas frescas"
Clasificacion.create :codigo => "1124", :nombre => "Cultivo de legumbres"
Clasificacion.create :codigo => "1125", :nombre => "Cultivo de flores y plantas ornamentales"
Clasificacion.create :codigo => "1131", :nombre => "Cultivo de frutas de pepita"
Clasificacion.create :codigo => "1132", :nombre => "Cultivo de frutas de carozo"
Clasificacion.create :codigo => "1133", :nombre => "Cultivo de frutas citricas"
Clasificacion.create :codigo => "1134", :nombre => "Cultivo de nueces y frutas secas"
Clasificacion.create :codigo => "1139", :nombre => "Cultivo de frutas n.c.p."
Clasificacion.create :codigo => "1141", :nombre => "Cultivo de plantas para la obtencion de fibras"
Clasificacion.create :codigo => "1142", :nombre => "Cultivo de plantas sacariferas"
Clasificacion.create :codigo => "1143", :nombre => "Cultivo de vid para vinificar"
Clasificacion.create :codigo => "1144", :nombre => "Cultivo de plantas para preparar bebidas"
Clasificacion.create :codigo => "1145", :nombre => "Cultivo de tabaco"
Clasificacion.create :codigo => "1146", :nombre => "Cultivo de especias y de plantas aromaticas y medicinales"
Clasificacion.create :codigo => "1149", :nombre => "Cultivos industriales n.c.p."
Clasificacion.create :codigo => "1151", :nombre => "Produccion de semillas"
Clasificacion.create :codigo => "1152", :nombre => "Produccion de otras formas de propagacion de cultivos agricolas"
Clasificacion.create :codigo => "1211", :nombre => "Cria de ganado bovino -excepto en cabanas y para la produccion de leche-"
Clasificacion.create :codigo => "1212", :nombre => "Cria de ganado ovino -excepto en cabanas y para la produccion de lana-"
Clasificacion.create :codigo => "1213", :nombre => "Cria de ganado porcino -excepto en cabanas-"
Clasificacion.create :codigo => "1214", :nombre => "Cria de ganado equino -excepto en haras-"
Clasificacion.create :codigo => "1215", :nombre => "Cria de ganado caprino -excepto en cabanas y para la produccion de leche-"
Clasificacion.create :codigo => "1216", :nombre => "Cria de ganado en cabanas y haras"
Clasificacion.create :codigo => "1217", :nombre => "Produccion de leche"
Clasificacion.create :codigo => "1218", :nombre => "Produccion de lana y pelos de ganado"
Clasificacion.create :codigo => "1219", :nombre => "Cria de ganado n.c.p."
Clasificacion.create :codigo => "1221", :nombre => "Cria de aves de corral"
Clasificacion.create :codigo => "1222", :nombre => "Produccion de huevos"
Clasificacion.create :codigo => "1223", :nombre => "Apicultura"
Clasificacion.create :codigo => "1224", :nombre => "Cria de animales peliferos, piliferos y plumiferos"
Clasificacion.create :codigo => "1229", :nombre => "Cria de animales y obtencion de productos de origen animal, n.c.p."
Clasificacion.create :codigo => "1411", :nombre => "Servicios de maquinaria agricola, excepto los de cosecha mecanica"
Clasificacion.create :codigo => "1412", :nombre => "Servicios de cosecha mecanica"
Clasificacion.create :codigo => "1413", :nombre => "Servicios de contratistas de mano de obra agricola"
Clasificacion.create :codigo => "1419", :nombre => "Servicios agricolas n.c.p"
Clasificacion.create :codigo => "1421", :nombre => "Inseminacion artificial y servicios n.c.p. para mejorar la reproduccion de los animales y el rendimiento de sus productos"
Clasificacion.create :codigo => "1422", :nombre => "Servicios de contratistas de mano de obra pecuaria"
Clasificacion.create :codigo => "1429", :nombre => "Servicios pecuarios n.c.p."
Clasificacion.create :codigo => "1501", :nombre => "Caza y captura de animales vivos y repoblacion de animales de caza"
Clasificacion.create :codigo => "1502", :nombre => "Servicios para la caza"
Clasificacion.create :codigo => "2011", :nombre => "Plantacion de bosques"

Estado.create :nombre => "Activo",
              :descripcion => "Emprendimiento en actividad"
Estado.create :nombre => "Inactivo",
              :descripcion => "Emprendimiento fuera de actividad"
Estado.create :nombre => "Gestion",
              :descripcion => "Emprendimiento en gestion aun no activo"

usuario = Administrador.new :email => "emprender@hamekoz.com.ar",
  :password               => "admin123456",
  :password_confirmation  => "admin123456",
  :nombre                 => "Administrador",
  :apellido               => "Emprender",
  :aceptado               => true
usuario.confirmed_at = DateTime.now
usuario.skip_confirmation!
usuario.save
usuario.unlock_access!
