Barrio.create :nombre => "9 de julio"
Barrio.create :nombre => "Aeropuerto"
Barrio.create :nombre => "Aeroparque"
Barrio.create :nombre => "Alfar"
Barrio.create :nombre => "Ameghino"
Barrio.create :nombre => "Antartida Argentina"
Barrio.create :nombre => "Barrio 180"
Barrio.create :nombre => "Batan"
Barrio.create :nombre => "Bernardino Rivadavia"
Barrio.create :nombre => "Belgrano"
Barrio.create :nombre => "Belisario Roldan"
Barrio.create :nombre => "Bosque Alegre"
Barrio.create :nombre => "Bosque Peralta Ramos"
Barrio.create :nombre => "Caisamar"
Barrio.create :nombre => "Cerrito"
Barrio.create :nombre => "Cerrito Sur"
Barrio.create :nombre => "Cerrito San Salvador"
Barrio.create :nombre => "Colina Alegre"
Barrio.create :nombre => "Constitucion"
Barrio.create :nombre => "Coronel Dorrego"
Barrio.create :nombre => "Costa Azul"
Barrio.create :nombre => "Don Bosco"
Barrio.create :nombre => "Don Emilio"
Barrio.create :nombre => "Dorrego"
Barrio.create :nombre => "El Grosellar"
Barrio.create :nombre => "El Martillo"
Barrio.create :nombre => "El Progreso"
Barrio.create :nombre => "Estrada"
Barrio.create :nombre => "Faro"
Barrio.create :nombre => "J. Lopez de Gomara"
Barrio.create :nombre => "Juramento"
Barrio.create :nombre => "Las Avenidas"
Barrio.create :nombre => "Las Colinas de Peralta Ramos"
Barrio.create :nombre => "La Florida"
Barrio.create :nombre => "La Perla"
Barrio.create :nombre => "La Zulema"
Barrio.create :nombre => "Libertad"
Barrio.create :nombre => "Los Acantilados"
Barrio.create :nombre => "Los Pinares"
Barrio.create :nombre => "Los Tilos"
Barrio.create :nombre => "Los Troncos"
Barrio.create :nombre => "Lourdes"
Barrio.create :nombre => "Malvinas Argentinas"
Barrio.create :nombre => "Mar y Sol"
Barrio.create :nombre => "Newbery"
Barrio.create :nombre => "Nueva Pompeya"
Barrio.create :nombre => "Montemar"
Barrio.create :nombre => "Parque Hermoso"
Barrio.create :nombre => "Parque La Florida"
Barrio.create :nombre => "Parque Luro"
Barrio.create :nombre => "Parque Palermo"
Barrio.create :nombre => "Parque Pena"
Barrio.create :nombre => "Peralta Ramos Oeste"
Barrio.create :nombre => "Pinos de Anchorena"
Barrio.create :nombre => "Playa Chapadmalal"
Barrio.create :nombre => "Playa Grande"
Barrio.create :nombre => "Playa Los Lobos"
Barrio.create :nombre => "Playa Serena"
Barrio.create :nombre => "Primera Junta"
Barrio.create :nombre => "Punta Mogotes"
Barrio.create :nombre => "San Antonio"
Barrio.create :nombre => "San Carlos"
Barrio.create :nombre => "San Eduardo"
Barrio.create :nombre => "San Geronimo"
Barrio.create :nombre => "San Jacinto"
Barrio.create :nombre => "San Jose"
Barrio.create :nombre => "San Juan"
Barrio.create :nombre => "San Martin"
Barrio.create :nombre => "San Patricio"
Barrio.create :nombre => "San Salvador"
Barrio.create :nombre => "Santa Monica"
Barrio.create :nombre => "Santa Rita"
Barrio.create :nombre => "Santa Rosa de Lima"
Barrio.create :nombre => "Santa Rosa del Mar"
Barrio.create :nombre => "Sarmiento"
Barrio.create :nombre => "Stella Maris"
Barrio.create :nombre => "Termas Huinco"
Barrio.create :nombre => "Villa Primera"
Barrio.create :nombre => "Zacagnini"

Rubro.create :nombre => "Artesanias"
Rubro.create :nombre => "Bazar"
Rubro.create :nombre => "Hogar"
Rubro.create :nombre => "Decoracion"
Rubro.create :nombre => "Entretenimiento"
Rubro.create :nombre => "Juguetes"
Rubro.create :nombre => "Gastronomia"
Rubro.create :nombre => "Alimentos y bebidas"
Rubro.create :nombre => "Grafica / Imprenta"
Rubro.create :nombre => "Informatica"
Rubro.create :nombre => "Electronica"
Rubro.create :nombre => "Textil: bebes y ninos"
Rubro.create :nombre => "Textil: adultos"
Rubro.create :nombre => "Textil: varios"
Rubro.create :nombre => "Salud y belleza"
Rubro.create :nombre => "Servicios"

Estado.create :nombre => "Activo",
              :descripcion => "Emprendimiento en actividad"
Estado.create :nombre => "Inactivo",
              :descripcion => "Emprendimiento fuera de actividad"
Estado.create :nombre => "Gestion",
              :descripcion => "Emprendimiento en gestion aun no activo"

Clasificacion.create :codigo => "1112", :nombre => "Cultivo de cereales forrajeros"
Clasificacion.create :codigo => "1113", :nombre => "Cultivo de oleaginosas excepto el de semillas para siembra"
Clasificacion.create :codigo => "1114", :nombre => "Cultivo de pastos forrajeros"
Clasificacion.create :codigo => "1121", :nombre => "Cultivo de papa, batata y mandioca"
Clasificacion.create :codigo => "1122", :nombre => "Cultivo de bulbos, brotes, raices y hortalizas de fruto"
Clasificacion.create :codigo => "1123", :nombre => "Cultivo de hortalizas de hoja y de otras hortalizas frescas"
Clasificacion.create :codigo => "1124", :nombre => "Cultivo de legumbres"
Clasificacion.create :codigo => "1125", :nombre => "Cultivo de flores y plantas ornamentales"
Clasificacion.create :codigo => "1131", :nombre => "Cultivo de frutas de pepita"
Clasificacion.create :codigo => "1132", :nombre => "Cultivo de frutas de carozo"
Clasificacion.create :codigo => "1133", :nombre => "Cultivo de frutas citricas"
Clasificacion.create :codigo => "1134", :nombre => "Cultivo de nueces y frutas secas"
Clasificacion.create :codigo => "1139", :nombre => "Cultivo de frutas n.c.p."
Clasificacion.create :codigo => "1141", :nombre => "Cultivo de plantas para la obtencion de fibras"
Clasificacion.create :codigo => "1142", :nombre => "Cultivo de plantas sacariferas"
Clasificacion.create :codigo => "1143", :nombre => "Cultivo de vid para vinificar"
Clasificacion.create :codigo => "1144", :nombre => "Cultivo de plantas para preparar bebidas"
Clasificacion.create :codigo => "1145", :nombre => "Cultivo de tabaco"
Clasificacion.create :codigo => "1146", :nombre => "Cultivo de especias y de plantas aromaticas y medicinales"
Clasificacion.create :codigo => "1149", :nombre => "Cultivos industriales n.c.p."
Clasificacion.create :codigo => "1151", :nombre => "Produccion de semillas"
Clasificacion.create :codigo => "1152", :nombre => "Produccion de otras formas de propagacion de cultivos agricolas"
Clasificacion.create :codigo => "1211", :nombre => "Cria de ganado bovino -excepto en cabanas y para la produccion de leche-"
Clasificacion.create :codigo => "1212", :nombre => "Cria de ganado ovino -excepto en cabanas y para la produccion de lana-"
Clasificacion.create :codigo => "1213", :nombre => "Cria de ganado porcino -excepto en cabanas-"
Clasificacion.create :codigo => "1214", :nombre => "Cria de ganado equino -excepto en haras-"
Clasificacion.create :codigo => "1215", :nombre => "Cria de ganado caprino -excepto en cabanas y para la produccion de leche-"
Clasificacion.create :codigo => "1216", :nombre => "Cria de ganado en cabanas y haras"
Clasificacion.create :codigo => "1217", :nombre => "Produccion de leche"
Clasificacion.create :codigo => "1218", :nombre => "Produccion de lana y pelos de ganado"
Clasificacion.create :codigo => "1219", :nombre => "Cria de ganado n.c.p."
Clasificacion.create :codigo => "1221", :nombre => "Cria de aves de corral"
Clasificacion.create :codigo => "1222", :nombre => "Produccion de huevos"
Clasificacion.create :codigo => "1223", :nombre => "Apicultura"
Clasificacion.create :codigo => "1224", :nombre => "Cria de animales peliferos, piliferos y plumiferos"
Clasificacion.create :codigo => "1229", :nombre => "Cria de animales y obtencion de productos de origen animal, n.c.p."
Clasificacion.create :codigo => "1411", :nombre => "Servicios de maquinaria agricola, excepto los de cosecha mecanica"
Clasificacion.create :codigo => "1412", :nombre => "Servicios de cosecha mecanica"
Clasificacion.create :codigo => "1413", :nombre => "Servicios de contratistas de mano de obra agricola"
Clasificacion.create :codigo => "1419", :nombre => "Servicios agricolas n.c.p"
Clasificacion.create :codigo => "1421", :nombre => "Inseminacion artificial y servicios n.c.p. para mejorar la reproduccion de los animales y el rendimiento de sus productos"
Clasificacion.create :codigo => "1422", :nombre => "Servicios de contratistas de mano de obra pecuaria"
Clasificacion.create :codigo => "1429", :nombre => "Servicios pecuarios n.c.p."
Clasificacion.create :codigo => "1501", :nombre => "Caza y captura de animales vivos y repoblacion de animales de caza"
Clasificacion.create :codigo => "1502", :nombre => "Servicios para la caza"
Clasificacion.create :codigo => "2011", :nombre => "Plantacion de bosques"
Clasificacion.create :codigo => "2012", :nombre => "Repoblacion y conservacion de bosques nativos y zonas forestadas"
Clasificacion.create :codigo => "2013", :nombre => "Explotacion de viveros forestales"
Clasificacion.create :codigo => "2021", :nombre => "Extraccion de productos forestales de bosques cultivados"
Clasificacion.create :codigo => "2022", :nombre => "Extraccion de productos forestales de bosques nativos"
Clasificacion.create :codigo => "2031", :nombre => "Servicios forestales de extraccion de madera"
Clasificacion.create :codigo => "2039", :nombre => "Servicios forestales excepto los relacionados con la extraccion de madera"
Clasificacion.create :codigo => "5011", :nombre => "Pesca maritima, costera y de altura"
Clasificacion.create :codigo => "5012", :nombre => "Pesca continental : fluvial y lacustre"
Clasificacion.create :codigo => "5013", :nombre => "Recoleccion de productos marinos"
Clasificacion.create :codigo => "5020", :nombre => "Explotacion de criaderos de peces, granjas piscicolas y otros frutos acuaticos (acuicultura)"
Clasificacion.create :codigo => "5030", :nombre => "Servicios para la pesca"
Clasificacion.create :codigo => "10100", :nombre => "Extraccion y aglomeracion de carbon"
Clasificacion.create :codigo => "10200", :nombre => "Extraccion y aglomeracion de lignito"
Clasificacion.create :codigo => "10300", :nombre => "Extraccion y aglomeracion de turba"
Clasificacion.create :codigo => "11100", :nombre => "Extraccion de petroleo crudo y gas natural"
Clasificacion.create :codigo => "11200", :nombre => "Actividades de servicios relacionadas con la extraccion de petroleo y gas, excepto las actividades de prospeccion"
Clasificacion.create :codigo => "12000", :nombre => "Extraccion de minerales y concentrados de uranio y torio"
Clasificacion.create :codigo => "13100", :nombre => "Extraccion de minerales de hierro"
Clasificacion.create :codigo => "13200", :nombre => "Extraccion de minerales metaliferos no ferrosos, excepto minerales de uranio y torio"
Clasificacion.create :codigo => "14110", :nombre => "Extraccion de rocas ornamentales"
Clasificacion.create :codigo => "14120", :nombre => "Extraccion de piedra caliza y yeso"
Clasificacion.create :codigo => "14130", :nombre => "Extraccion de arenas, canto rodado y triturados petreos"
Clasificacion.create :codigo => "14140", :nombre => "Extraccion de arcilla y caolin"
Clasificacion.create :codigo => "14211", :nombre => "Extraccion de minerales para la fabricacion de abonos excepto turba"
Clasificacion.create :codigo => "14212", :nombre => "Extraccion de minerales para la fabricacion de productos quimicos"
Clasificacion.create :codigo => "14220", :nombre => "Extraccion de sal en salinas y de roca"
Clasificacion.create :codigo => "14290", :nombre => "Explotacion de minas y canteras n.c.p."
Clasificacion.create :codigo => "15111", :nombre => "Matanza de ganado bovino y procesamiento de su carne"
Clasificacion.create :codigo => "15112", :nombre => "Produccion y procesamiento de carne de aves"
Clasificacion.create :codigo => "15113", :nombre => "Elaboracion de fiambres y embutidos"
Clasificacion.create :codigo => "15114", :nombre => "Matanza de ganado excepto el bovino y procesamiento de su carne"
Clasificacion.create :codigo => "15119", :nombre => "Matanza de animales n.c.p. y procesamiento de su carne; Elaboracion de subproductos carnicos n.c.p."
Clasificacion.create :codigo => "15120", :nombre => "Elaboracion de pescado y productos de pescado"
Clasificacion.create :codigo => "15131", :nombre => "Preparacion de conservas de frutas, hortalizas y legumbres"
Clasificacion.create :codigo => "15132", :nombre => "Elaboracion de jugos naturales y sus concentrados, de frutas, hortalizas y legumbres"
Clasificacion.create :codigo => "15133", :nombre => "Elaboracion de pulpas, jaleas, dulces y mermeladas"
Clasificacion.create :codigo => "15134", :nombre => "Elaboracion de frutas, hortalizas y legumbres congeladas"
Clasificacion.create :codigo => "15139", :nombre => "Elaboracion de frutas, hortalizas y legumbres deshidratadas o desecadas; preparacion n.c.p. de frutas, hortalizas y legumbres"
Clasificacion.create :codigo => "15141", :nombre => "Elaboracion de aceites y grasas de origen vegetal sin refinar y sus subproductos; elaboracion de aceite virgen"
Clasificacion.create :codigo => "15142", :nombre => "Elaboracion de aceites y grasas de origen vegetal refinadas"
Clasificacion.create :codigo => "15143", :nombre => "Elaboracion de margarinas y grasas vegetales comestibles similares"
Clasificacion.create :codigo => "15201", :nombre => "Elaboracion de leches y productos lacteos deshidratados"
Clasificacion.create :codigo => "15202", :nombre => "Elaboracion de quesos"
Clasificacion.create :codigo => "15203", :nombre => "Elaboracion industrial de helados"
Clasificacion.create :codigo => "15209", :nombre => "Elaboracion de productos l cteos n.c.p."
Clasificacion.create :codigo => "15311", :nombre => "Molienda de trigo"
Clasificacion.create :codigo => "15312", :nombre => "Preparacion de arroz"
Clasificacion.create :codigo => "15313", :nombre => "Preparacion y molienda de legumbres y cereales -excepto trigo-"
Clasificacion.create :codigo => "15320", :nombre => "Elaboracion de almidones y productos derivados del almidon"
Clasificacion.create :codigo => "15330", :nombre => "Elaboracion de alimentos preparados para animales"
Clasificacion.create :codigo => "15411", :nombre => "Elaboracion de galletitas y bizcochos"
Clasificacion.create :codigo => "15412", :nombre => "Elaboracion industrial de productos de panaderia, excluido galletitas y bizcochos"
Clasificacion.create :codigo => "15419", :nombre => "Elaboracion de productos de panaderia n.c.p."
Clasificacion.create :codigo => "15420", :nombre => "Elaboracion de az£car"
Clasificacion.create :codigo => "15430", :nombre => "Elaboracion de cacao y chocolate y de productos de confiteria"
Clasificacion.create :codigo => "15441", :nombre => "Elaboracion de pastas alimenticias frescas"
Clasificacion.create :codigo => "15442", :nombre => "Elaboracion de pastas alimenticias secas"
Clasificacion.create :codigo => "15491", :nombre => "Tostado, torrado y molienda de caf‚; elaboracion y molienda de hierbas arom ticas y especias"
Clasificacion.create :codigo => "15492", :nombre => "Preparacion de hojas de t‚"
Clasificacion.create :codigo => "15493", :nombre => "Elaboracion de yerba mate"
Clasificacion.create :codigo => "15499", :nombre => "Elaboracion de productos alimenticios n.c.p."
Clasificacion.create :codigo => "15511", :nombre => "Destilacion de alcohol etilico"
Clasificacion.create :codigo => "15512", :nombre => "Destilacion, rectificacion y mezcla de bebidas espiritosas"
Clasificacion.create :codigo => "15521", :nombre => "Elaboracion de vinos"
Clasificacion.create :codigo => "15529", :nombre => "Elaboracion de sidra y otras bebidas alcoholicas fermentadas a partir de frutas"
Clasificacion.create :codigo => "15530", :nombre => "Elaboracion de cerveza, bebidas malteadas y de malta"
Clasificacion.create :codigo => "15541", :nombre => "Elaboracion de soda y aguas"
Clasificacion.create :codigo => "15542", :nombre => "Elaboracion de bebidas gaseosas, excepto soda"
Clasificacion.create :codigo => "15549", :nombre => "Elaboracion de hielo, jugos envasados para diluir y otras bebidas no alcoholicas"
Clasificacion.create :codigo => "16001", :nombre => "Preparacion de hojas de tabaco"
Clasificacion.create :codigo => "16009", :nombre => "Elaboracion de cigarrillos y productos de tabaco n.c.p."
Clasificacion.create :codigo => "17111", :nombre => "Preparacion de fibras textiles vegetales; desmotado de algodon"
Clasificacion.create :codigo => "17112", :nombre => "Lavado de lana"
Clasificacion.create :codigo => "17113", :nombre => "Fabricacion de hilados de fibras textiles"
Clasificacion.create :codigo => "17114", :nombre => "Fabricacion de tejidos textiles, incluso en hilanderias y tejedurias integradas"
Clasificacion.create :codigo => "17120", :nombre => "Acabado de productos textiles"
Clasificacion.create :codigo => "17210", :nombre => "Fabricacion de articulos confeccionados de materiales textiles, excepto prendas de vestir"
Clasificacion.create :codigo => "17220", :nombre => "Fabricacion de tapices y alfombras"
Clasificacion.create :codigo => "17230", :nombre => "Fabricacion de cuerdas, cordeles, bramantes y redes"
Clasificacion.create :codigo => "17290", :nombre => "Fabricacion de productos textiles n.c.p."
Clasificacion.create :codigo => "17301", :nombre => "Fabricacion de medias"
Clasificacion.create :codigo => "17302", :nombre => "Fabricacion de su‚teres y articulos similares de punto"
Clasificacion.create :codigo => "17309", :nombre => "Fabricacion de tejidos y articulos de punto n.c.p."
Clasificacion.create :codigo => "18111", :nombre => "Confeccion de ropa interior, prendas para dormir y para la playa"
Clasificacion.create :codigo => "18112", :nombre => "Confeccion de indumentaria de trabajo, uniformes y guardapolvos"
Clasificacion.create :codigo => "18113", :nombre => "Confeccion de indumentaria para beb‚s y ninos"
Clasificacion.create :codigo => "18119", :nombre => "Fabricacion de prendas de vestir n.c.p., excepto prendas de piel y de cuero"
Clasificacion.create :codigo => "18120", :nombre => "Confeccion de prendas y accesorios de vestir de cuero"
Clasificacion.create :codigo => "18200", :nombre => "Terminacion y tenido de pieles; fabricacion de articulos de piel"
Clasificacion.create :codigo => "19110", :nombre => "Curtido y terminacion de cueros"
Clasificacion.create :codigo => "19120", :nombre => "Fabricacion de maletas, bolsos de mano y similares, articulos de talabarteria y articulos de cuero n.c.p."
Clasificacion.create :codigo => "19201", :nombre => "Fabricacion de calzado de cuero, excepto el ortop‚dico"
Clasificacion.create :codigo => "19202", :nombre => "Fabricacion de calzado de tela, pl stico, goma, caucho y otros materiales, excepto calzado ortop‚dico y de asbesto"
Clasificacion.create :codigo => "19203", :nombre => "Fabricacion de partes de calzado"
Clasificacion.create :codigo => "20100", :nombre => "Aserrado y cepillado de madera"
Clasificacion.create :codigo => "20210", :nombre => "Fabricacion de hojas de madera para enchapado; fabricacion de tableros contrachapados; tableros laminados; tableros de partculas y tableros y paneles n.c.p"
Clasificacion.create :codigo => "20220", :nombre => "Fabricacion de partes y piezas de carpinteria para edificios y construcciones"
Clasificacion.create :codigo => "20230", :nombre => "Fabricacion de recipientes de madera"
Clasificacion.create :codigo => "20290", :nombre => "Fabricacion de productos de madera n.c.p.; fabricacion de articulos de corcho, paja y materiales trenzables"
Clasificacion.create :codigo => "21010", :nombre => "Fabricacion de pasta de madera, papel y carton"
Clasificacion.create :codigo => "21020", :nombre => "Fabricacion de papel y carton ondulado y de envases de papel y carton"
Clasificacion.create :codigo => "21091", :nombre => "Fabricacion de articulos de papel y carton de uso dom‚stico e higi‚nico sanitario"
Clasificacion.create :codigo => "21099", :nombre => "Fabricacion de articulos de papel y carton n.c.p."
Clasificacion.create :codigo => "22110", :nombre => "Edicion de libros, folletos, partituras y otras publicaciones"
Clasificacion.create :codigo => "22120", :nombre => "Edicion de periodicos, revistas y publicaciones periodicas"
Clasificacion.create :codigo => "22130", :nombre => "Edicion de grabaciones"
Clasificacion.create :codigo => "22190", :nombre => "Edicion n.c.p."
Clasificacion.create :codigo => "22210", :nombre => "Impresion"
Clasificacion.create :codigo => "22220", :nombre => "Servicios relacionados con la impresion"
Clasificacion.create :codigo => "22300", :nombre => "Reproduccion de grabaciones"
Clasificacion.create :codigo => "23100", :nombre => "Fabricacion de productos de hornos de coque"
Clasificacion.create :codigo => "23200", :nombre => "Fabricacion de productos de la refinacion del petroleo"
Clasificacion.create :codigo => "23300", :nombre => "Fabricacion de combustible nuclear"
Clasificacion.create :codigo => "24111", :nombre => "Fabricacion de gases comprimidos y licuados."
Clasificacion.create :codigo => "24112", :nombre => "Fabricacion de curtientes naturales y sint‚ticos."
Clasificacion.create :codigo => "24113", :nombre => "Fabricacion de materias colorantes b sicas, excepto pigmentos preparados."
Clasificacion.create :codigo => "24118", :nombre => "Fabricacion de materias quimicas inorg nicas b sicas, n.c.p."
Clasificacion.create :codigo => "24119", :nombre => "Fabricacion de materias quimicas org nicas b sicas, n.c.p."
Clasificacion.create :codigo => "24120", :nombre => "Fabricacion de abonos y compuestos de nitrogeno"
Clasificacion.create :codigo => "24130", :nombre => "Fabricacion de pl sticos en formas primarias y de caucho sint‚tico"
Clasificacion.create :codigo => "24210", :nombre => "Fabricacion de plaguicidas y productos quimicos de uso agropecuario"
Clasificacion.create :codigo => "24220", :nombre => "Fabricacion de pinturas; barnices y productos de revestimiento similares; tintas de imprenta y masillas"
Clasificacion.create :codigo => "24231", :nombre => "Fabricacion de medicamentos de uso humano y productos farmac‚uticos"
Clasificacion.create :codigo => "24232", :nombre => "Fabricacion de medicamentos de uso veterinario"
Clasificacion.create :codigo => "24239", :nombre => "Fabricacion de productos de laboratorio, sustancias quimicas medicinales y productos bot nicos n.c.p."
Clasificacion.create :codigo => "24241", :nombre => "Fabricacion de jabones y preparados de limpieza"
Clasificacion.create :codigo => "24249", :nombre => "Fabricacion de cosm‚ticos, perfumes y productos de higiene y tocador"
Clasificacion.create :codigo => "24290", :nombre => "Fabricacion de productos quimicos n.c.p."
Clasificacion.create :codigo => "24300", :nombre => "Fabricacion de fibras manufacturadas"
Clasificacion.create :codigo => "25111", :nombre => "Fabricacion de cubiertas y c maras"
Clasificacion.create :codigo => "25112", :nombre => "Recauchutado y renovacion de cubiertas"
Clasificacion.create :codigo => "25190", :nombre => "Fabricacion de productos de caucho n.c.p."
Clasificacion.create :codigo => "25201", :nombre => "Fabricacion de envases pl sticos"
Clasificacion.create :codigo => "25209", :nombre => "Fabricacion de productos pl sticos en formas b sicas y articulos de pl stico n.c.p., excepto muebles"
Clasificacion.create :codigo => "26101", :nombre => "Fabricacion de envases de vidrio"
Clasificacion.create :codigo => "26102", :nombre => "Fabricacion y elaboracion de vidrio plano"
Clasificacion.create :codigo => "26109", :nombre => "Fabricacion de productos de vidrio n.c.p."
Clasificacion.create :codigo => "26911", :nombre => "Fabricacion de articulos sanitarios de cer mica"
Clasificacion.create :codigo => "26919", :nombre => "Fabricacion de articulos de cer mica no refractaria para uso no estructural n.c.p."
Clasificacion.create :codigo => "26920", :nombre => "Fabricacion de productos de cer mica refractaria"
Clasificacion.create :codigo => "26930", :nombre => "Fabricacion de productos de arcilla y cer mica no refractaria para uso estructural"
Clasificacion.create :codigo => "26941", :nombre => "Elaboracion de cemento"
Clasificacion.create :codigo => "26942", :nombre => "Elaboracion de cal y yeso"
Clasificacion.create :codigo => "26951", :nombre => "Fabricacion de mosaicos"
Clasificacion.create :codigo => "26959", :nombre => "Fabricacion de articulos de cemento, fibrocemento y yeso excepto mosaicos"
Clasificacion.create :codigo => "26960", :nombre => "Corte, tallado y acabado de la piedra"
Clasificacion.create :codigo => "26991", :nombre => "Elaboracion primaria n.c.p. de minerales no met licos"
Clasificacion.create :codigo => "26999", :nombre => "Fabricacion de productos minerales no met licos n.c.p."
Clasificacion.create :codigo => "27100", :nombre => "Industrias b sicas de hierro y acero"
Clasificacion.create :codigo => "27201", :nombre => "Elaboracion de aluminio primario y semielaborados de aluminio"
Clasificacion.create :codigo => "27209", :nombre => "Produccion de metales no ferrosos n.c.p. y sus semielaborados"
Clasificacion.create :codigo => "27310", :nombre => "Fundicion de hierro y acero"
Clasificacion.create :codigo => "27320", :nombre => "Fundicion de metales no ferrosos"
Clasificacion.create :codigo => "28110", :nombre => "Fabricacion de productos met licos para uso estructural y montaje estructural"
Clasificacion.create :codigo => "28120", :nombre => "Fabricacion de tanques, depositos y recipientes de metal"
Clasificacion.create :codigo => "28130", :nombre => "Fabricacion de generadores de vapor"
Clasificacion.create :codigo => "28910", :nombre => "Forjado, prensado, estampado y laminado de metales; pulvimetalurgia"
Clasificacion.create :codigo => "28920", :nombre => "Tratamiento y revestimiento de metales; obras de ingenieria mec nica en general realizadas a cambio de una retribuci•n por contrataci•n"
Clasificacion.create :codigo => "28930", :nombre => "Fabricacion de articulos de cuchilleria, herramientas de mano y articulos de ferreteria"
Clasificacion.create :codigo => "28991", :nombre => "Fabricacion de envases met licos"
Clasificacion.create :codigo => "28999", :nombre => "Fabricacion de productos met licos n.c.p."
Clasificacion.create :codigo => "29110", :nombre => "Fabricacion de motores y turbinas, excepto motores para aeronaves, vehiculos automotores y motocicletas"
Clasificacion.create :codigo => "29120", :nombre => "Fabricacion de bombas; compresores; grifos y v lvulas"
Clasificacion.create :codigo => "29130", :nombre => "Fabricacion de cojinetes; engranajes; trenes de engranaje y piezas de transmision"
Clasificacion.create :codigo => "29140", :nombre => "Fabricacion de hornos; hogares y quemadores"
Clasificacion.create :codigo => "29150", :nombre => "Fabricacion de equipo de elevacion y manipulacion"
Clasificacion.create :codigo => "29190", :nombre => "Fabricacion de maquinaria de uso general n.c.p."
Clasificacion.create :codigo => "29211", :nombre => "Fabricacion de tractores"
Clasificacion.create :codigo => "29219", :nombre => "Fabricacion de maquinaria agropecuaria y forestal, excepto tractores"
Clasificacion.create :codigo => "29220", :nombre => "Fabricacion de m quinas herramienta"
Clasificacion.create :codigo => "29230", :nombre => "Fabricacion de maquinaria metal£rgica"
Clasificacion.create :codigo => "29240", :nombre => "Fabricacion de maquinaria para la explotacion de minas y canteras y para obras de construccion"
Clasificacion.create :codigo => "29250", :nombre => "Fabricacion de maquinaria para la elaboracion de alimentos, bebidas y tabaco"
Clasificacion.create :codigo => "29260", :nombre => "Fabricacion de maquinaria para la elaboracion de productos textiles, prendas de vestir y cueros"
Clasificacion.create :codigo => "29270", :nombre => "Fabricacion de armas y municiones"
Clasificacion.create :codigo => "29290", :nombre => "Fabricacion de maquinaria de uso especial n.c.p."
Clasificacion.create :codigo => "29301", :nombre => "Fabricacion de cocinas, calefones, estufas y calefactores no el‚ctricos"
Clasificacion.create :codigo => "29302", :nombre => "Fabricacion de heladeras, freezers, lavarropas y secarropas"
Clasificacion.create :codigo => "29309", :nombre => "Fabricacion de aparatos de uso dom‚stico n.c.p."
Clasificacion.create :codigo => "30000", :nombre => "Fabricacion de maquinaria de oficina, contabilidad e inform tica"
Clasificacion.create :codigo => "31100", :nombre => "Fabricacion de motores, generadores y transformadores el‚ctricos"
Clasificacion.create :codigo => "31200", :nombre => "Fabricacion de aparatos de distribucion y control de la energia el‚ctrica"
Clasificacion.create :codigo => "31300", :nombre => "Fabricacion de hilos y cables aislados"
Clasificacion.create :codigo => "31400", :nombre => "Fabricacion de acumuladores, pilas y baterias primarias"
Clasificacion.create :codigo => "31500", :nombre => "Fabricacion de l mparas el‚ctricas y equipo de iluminacion"
Clasificacion.create :codigo => "31900", :nombre => "Fabricacion de equipo el‚ctrico n.c.p."
Clasificacion.create :codigo => "32100", :nombre => "Fabricacion de tubos, v lvulas y otros componentes electronicos"
Clasificacion.create :codigo => "32200", :nombre => "Fabricacion de transmisores de radio y television y de aparatos para telefonia y telegrafia con hilos"
Clasificacion.create :codigo => "32300", :nombre => "Fabricacion de receptores de radio y television, aparatos de grabacion y reproduccion de sonido y video, y productos conexos"
Clasificacion.create :codigo => "33110", :nombre => "Fabricacion de equipo m‚dico y quir£rgico y de aparatos ortop‚dicos"
Clasificacion.create :codigo => "33120", :nombre => "Fabricacion de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, excepto el equipo de control procesos industriales"
Clasificacion.create :codigo => "33130", :nombre => "Fabricacion de equipo de control de procesos industriales"
Clasificacion.create :codigo => "33200", :nombre => "Fabricacion de instrumentos de optica y equipo fotogr fico"
Clasificacion.create :codigo => "33300", :nombre => "Fabricacion de relojes"
Clasificacion.create :codigo => "34100", :nombre => "Fabricacion de vehiculos automotores"
Clasificacion.create :codigo => "34200", :nombre => "Fabricacion de carrocerias para vehiculos automotores; fabricacion de remolques y semirremolques"
Clasificacion.create :codigo => "34300", :nombre => "Fabricacion de partes; piezas y accesorios para vehiculos automotores y sus motores"
Clasificacion.create :codigo => "35110", :nombre => "Construccion y reparacion de buques"
Clasificacion.create :codigo => "35120", :nombre => "Construccion y reparacion de embarcaciones de recreo y deporte"
Clasificacion.create :codigo => "35200", :nombre => "Fabricacion de locomotoras y de material rodante para ferrocarriles y tranvias"
Clasificacion.create :codigo => "35300", :nombre => "Fabricacion y reparacion de aeronaves"
Clasificacion.create :codigo => "35910", :nombre => "Fabricacion de motocicletas"
Clasificacion.create :codigo => "35920", :nombre => "Fabricacion de bicicletas y de sillones de ruedas ortop‚dicos"
Clasificacion.create :codigo => "35990", :nombre => "Fabricacion de equipo de transporte n.c.p."
Clasificacion.create :codigo => "36101", :nombre => "Fabricacion de muebles y partes de muebles, principalmente de madera"
Clasificacion.create :codigo => "36102", :nombre => "Fabricacion de muebles y partes de muebles, excepto los que son principalmente de madera"
Clasificacion.create :codigo => "36103", :nombre => "Fabricacion de somieres y colchones"
Clasificacion.create :codigo => "36910", :nombre => "Fabricacion de joyas y articulos conexos"
Clasificacion.create :codigo => "36920", :nombre => "Fabricacion de instrumentos de m£sica"
Clasificacion.create :codigo => "36930", :nombre => "Fabricacion de articulos de deporte"
Clasificacion.create :codigo => "36940", :nombre => "Fabricacion de juegos y juguetes"
Clasificacion.create :codigo => "36991", :nombre => "Fabricacion de l pices, lapiceras, boligrafos, sellos y articulos similares para oficinas y artistas"
Clasificacion.create :codigo => "36992", :nombre => "Fabricacion de cepillos y pinceles"
Clasificacion.create :codigo => "36999", :nombre => "Industrias manufactureras n.c.p."
Clasificacion.create :codigo => "37100", :nombre => "Reciclamiento de desperdicios y desechos met licos"
Clasificacion.create :codigo => "37200", :nombre => "Reciclamiento de desperdicios y desechos no met licos"
Clasificacion.create :codigo => "40111", :nombre => "Generacion de energia t‚rmica convencional"
Clasificacion.create :codigo => "40112", :nombre => "Generacion de energia t‚rmica nuclear"
Clasificacion.create :codigo => "40113", :nombre => "Generacion de energia hidr ulica"
Clasificacion.create :codigo => "40119", :nombre => "Generacion de energia n.c.p."
Clasificacion.create :codigo => "40120", :nombre => "Transporte de energia el‚ctrica"
Clasificacion.create :codigo => "40130", :nombre => "Distribucion de energia el‚ctrica"
Clasificacion.create :codigo => "40200", :nombre => "Fabricacion de gas y distribucion de combustibles gaseosos por tuberias"
Clasificacion.create :codigo => "40300", :nombre => "Suministro de vapor y agua caliente"
Clasificacion.create :codigo => "41001", :nombre => "Captacion, depuracion y distribucion de agua de fuentes subterr neas"
Clasificacion.create :codigo => "41002", :nombre => "Captacion, depuracion y distribucion de agua de fuentes superficiales"
Clasificacion.create :codigo => "45110", :nombre => "Demolicion y voladura de edificios y de sus partes"
Clasificacion.create :codigo => "45120", :nombre => "Perforacion y sondeo, excepto: perforacion de pozos de petroleo, de gas, de minas e hidr ulicos y prospecci•n de yacimientos de petroleo"
Clasificacion.create :codigo => "45190", :nombre => "Movimiento de suelos y preparacion de terrenos para obras n.c.p."
Clasificacion.create :codigo => "45210", :nombre => "Construccion, reforma y reparacion de edificios residenciales"
Clasificacion.create :codigo => "45220", :nombre => "Construccion, reforma y reparacion de edificios no residenciales"
Clasificacion.create :codigo => "45231", :nombre => "Construccion, reforma y reparacion de obras hidr ulicas"
Clasificacion.create :codigo => "45239", :nombre => "Construccion, reforma y reparacion de obras de infraestructura de transporte n.c.p. excepto los edificios para tr fico y comunicaciones, estaciones, terminales y edificios asociados"
Clasificacion.create :codigo => "45240", :nombre => "Construccion, reforma y reparacion de redes de electricidad, de gas, de agua, de telecomunicaciones y de otros servicios"
Clasificacion.create :codigo => "45251", :nombre => "Perforacion de pozos de agua"
Clasificacion.create :codigo => "45252", :nombre => "Actividades de hincado de pilotes, cimentacion y otros trabajos de hormigon armado"
Clasificacion.create :codigo => "45259", :nombre => "Actividades especializadas de construccion n.c.p."
Clasificacion.create :codigo => "45290", :nombre => "Obras de ingenieria civil n.c.p."
Clasificacion.create :codigo => "45311", :nombre => "Instalacion de ascensores, montacargas y escaleras mec nicas"
Clasificacion.create :codigo => "45312", :nombre => "Instalacion de sistemas de iluminacion, control y senalizacion el‚ctrica para el transporte"
Clasificacion.create :codigo => "45319", :nombre => "Ejecucion y mantenimiento de instalaciones el‚ctricas y electronicas n.c.p."
Clasificacion.create :codigo => "45320", :nombre => "Aislamiento t‚rmico, ac£stico, hidrico y antivibratorio"
Clasificacion.create :codigo => "45330", :nombre => "Instalaciones de gas, agua, sanitarios y de climatizacion, con sus artefactos conexos"
Clasificacion.create :codigo => "45390", :nombre => "Instalaciones para edificios y obras de ingenieria civil n.c.p."
Clasificacion.create :codigo => "45410", :nombre => "Instalaciones de carpinteria, herreria de obra y artistica"
Clasificacion.create :codigo => "45420", :nombre => "Terminacion y revestimiento de paredes y pisos"
Clasificacion.create :codigo => "45430", :nombre => "Colocacion de cristales en obra"
Clasificacion.create :codigo => "45440", :nombre => "Pintura y trabajos de decoracion"
Clasificacion.create :codigo => "45490", :nombre => "Terminacion de edificios y obras de ingenieria civil n.c.p."
Clasificacion.create :codigo => "45500", :nombre => "Alquiler de equipo de construccion o demolicion dotado de operarios"
Clasificacion.create :codigo => "50111", :nombre => "Venta de autos, camionetas y utilitarios, nuevos"
Clasificacion.create :codigo => "50119", :nombre => "Venta de vehiculos automotores, nuevos n.c.p."
Clasificacion.create :codigo => "50121", :nombre => "Venta de autos, camionetas y utilitarios usados"
Clasificacion.create :codigo => "50129", :nombre => "Venta de vehiculos automotores usados n.c.p."
Clasificacion.create :codigo => "50210", :nombre => "Lavado autom tico y manual"
Clasificacion.create :codigo => "50221", :nombre => "Reparacion de c maras y cubiertas"
Clasificacion.create :codigo => "50222", :nombre => "Reparacion de amortiguadores, alineacion de direccion y balanceo de ruedas"
Clasificacion.create :codigo => "50230", :nombre => "Instalacion y reparacion de parabrisas, lunetas y ventanillas, alarmas, cerraduras, radios, sistemas de climatizacion automotor y grabado de cristales"
Clasificacion.create :codigo => "50240", :nombre => "Tapizado y retapizado"
Clasificacion.create :codigo => "50250", :nombre => "Reparaciones el‚ctricas, del tablero e instrumental; reparacion y recarga de baterias"
Clasificacion.create :codigo => "50260", :nombre => "Reparacion y pintura de carrocerias; colocacion y reparacion de guardabarros y protecciones exteriores"
Clasificacion.create :codigo => "50291", :nombre => "Instalacion y reparacion de canos de escape"
Clasificacion.create :codigo => "50292", :nombre => "Mantenimiento y reparacion de frenos"
Clasificacion.create :codigo => "50299", :nombre => "Mantenimiento y reparacion del motor n.c.p.; mec nica integral"
Clasificacion.create :codigo => "50310", :nombre => "Venta al por mayor de partes, piezas y accesorios de vehiculos automotores"
Clasificacion.create :codigo => "50321", :nombre => "Venta al por menor de c maras y cubiertas"
Clasificacion.create :codigo => "50322", :nombre => "Venta al por menor de baterias"
Clasificacion.create :codigo => "50329", :nombre => "Venta al por menor de partes, piezas y accesorios excepto c maras y cubiertas y baterias"
Clasificacion.create :codigo => "50401", :nombre => "Venta de motocicletas y de sus partes, piezas y accesorios"
Clasificacion.create :codigo => "50402", :nombre => "Mantenimiento y reparacion de motocicletas"
Clasificacion.create :codigo => "50500", :nombre => "Venta al por menor de combustible para vehiculos automotores y motocicletas"
Clasificacion.create :codigo => "51111", :nombre => "Venta al por mayor en comision o consignacion de productos agricolas"
Clasificacion.create :codigo => "51112", :nombre => "Venta al por mayor en comision o consignacion de productos pecuarios"
Clasificacion.create :codigo => "51191", :nombre => "Venta al por mayor en comision o consignacion de alimentos, bebidas y tabaco"
Clasificacion.create :codigo => "51192", :nombre => "Venta al por mayor en comision o consignacion de productos textiles, prendas de vestir, calzado excepto el ortop‚dico, articulos de marroquineria, paraguas y similares y productos de cuero n.c.p."
Clasificacion.create :codigo => "51193", :nombre => "Venta al por mayor en comision o consignacion de madera y materiales para la construccion"
Clasificacion.create :codigo => "51194", :nombre => "Venta al por mayor en comision o consignacion de energia el‚ctrica, gas y combustibles"
Clasificacion.create :codigo => "51195", :nombre => "Venta al por mayor en comision o consignacion de minerales, metales y productos quimicos industriales"
Clasificacion.create :codigo => "51196", :nombre => "Venta al por mayor en comision o consignacion de maquinaria, equipo profesional industrial y comercial, embarcaciones y aeronaves"
Clasificacion.create :codigo => "51197", :nombre => "Venta al por mayor en comision o consignacion de papel, carton, libros, revistas, diarios, materiales de embalaje y articulos de libreria"
Clasificacion.create :codigo => "51199", :nombre => "Venta al por mayor en comision o consignacion de mercaderias n.c.p."
Clasificacion.create :codigo => "51211", :nombre => "Venta al por mayor de materias primas agricolas y de la silvicultura"
Clasificacion.create :codigo => "51212", :nombre => "Venta al por mayor de materias primas pecuarias incluso animales vivos"
Clasificacion.create :codigo => "51221", :nombre => "Venta al por mayor de fiambres, quesos y productos l cteos"
Clasificacion.create :codigo => "51222", :nombre => "Venta al por mayor de carnes rojas, menudencias y chacinados frescos; productos de granja y de la caza"
Clasificacion.create :codigo => "51223", :nombre => "Venta al por mayor de pescado"
Clasificacion.create :codigo => "51224", :nombre => "Venta al por mayor y empaque de frutas, de legumbres y hortalizas frescas"
Clasificacion.create :codigo => "51225", :nombre => "Venta al por mayor de pan, productos de confiteria y pastas frescas"
Clasificacion.create :codigo => "51226", :nombre => "Venta al por mayor de chocolates, golosinas y productos para kioscos y polirrubros n.c.p., excepto cigarrillos"
Clasificacion.create :codigo => "51227", :nombre => "Venta al por mayor de aceites, az£car, caf‚, t‚, yerba mate y otras infusiones y especias y condimentos"
Clasificacion.create :codigo => "51229", :nombre => "Venta al por mayor de productos alimenticios n.c.p."
Clasificacion.create :codigo => "51231", :nombre => "Venta al por mayor de bebidas alcoholicas"
Clasificacion.create :codigo => "51232", :nombre => "Venta al por mayor de bebidas no alcoholicas"
Clasificacion.create :codigo => "51240", :nombre => "Venta al por mayor de cigarrillos y productos de tabaco"
Clasificacion.create :codigo => "51311", :nombre => "Venta al por mayor de productos textiles excepto prendas y accesorios de vestir"
Clasificacion.create :codigo => "51312", :nombre => "Venta al por mayor de prendas y accesorios de vestir"
Clasificacion.create :codigo => "51313", :nombre => "Venta al por mayor de calzado excepto el ortop‚dico"
Clasificacion.create :codigo => "51314", :nombre => "Venta al por mayor de articulos de cueros, pieles, marroquineria y talabarteria, paraguas y similares"
Clasificacion.create :codigo => "51321", :nombre => "Venta al por mayor de libros, revistas y diarios"
Clasificacion.create :codigo => "51322", :nombre => "Venta al por mayor de papel, carton, materiales de embalaje y articulos de libreria"
Clasificacion.create :codigo => "51331", :nombre => "Venta al por mayor de productos farmac‚uticos y veterinarios"
Clasificacion.create :codigo => "51332", :nombre => "Venta al por mayor de productos cosm‚ticos, de tocador y de perfumeria"
Clasificacion.create :codigo => "51333", :nombre => "Venta al por mayor de instrumental m‚dico y odontologico y articulos ortop‚dicos"
Clasificacion.create :codigo => "51341", :nombre => "Venta al por mayor de articulos de optica y de fotografia"
Clasificacion.create :codigo => "51342", :nombre => "Venta al por mayor de articulos de relojeria, joyeria y fantasias"
Clasificacion.create :codigo => "51351", :nombre => "Venta al por mayor de muebles excepto de oficina; articulos de mimbre y corcho; colchones y somieres"
Clasificacion.create :codigo => "51352", :nombre => "Venta al por mayor de articulos de iluminacion"
Clasificacion.create :codigo => "51353", :nombre => "Venta al por mayor de articulos de bazar y menaje"
Clasificacion.create :codigo => "51354", :nombre => "Venta al por mayor de artefactos para el hogar, el‚ctricos, a gas, kerosene u otros combustibles"
Clasificacion.create :codigo => "51355", :nombre => "Venta al por mayor de instrumentos musicales, equipos de sonido, casetes de audio y video, y discos de audio y video"
Clasificacion.create :codigo => "51391", :nombre => "Venta al por mayor de materiales y productos de limpieza"
Clasificacion.create :codigo => "51392", :nombre => "Venta al por mayor de juguetes"
Clasificacion.create :codigo => "51393", :nombre => "Venta al por mayor de bicicletas y rodados similares"
Clasificacion.create :codigo => "51394", :nombre => "Venta al por mayor de articulos de esparcimiento y deportes"
Clasificacion.create :codigo => "51395", :nombre => "Venta al por mayor de papeles para pared, revestimiento para pisos de goma, pl stico y textiles, y articulos similares para la decoracion"
Clasificacion.create :codigo => "51399", :nombre => "Venta al por mayor articulos de uso dom‚stico y/o personal n.c.p"
Clasificacion.create :codigo => "51411", :nombre => "Venta al por mayor de combustibles y lubricantes para automotores"
Clasificacion.create :codigo => "51419", :nombre => "Venta al por mayor de combustibles y lubricantes -excepto para automotores, gas en garrafas- lena y carbon"
Clasificacion.create :codigo => "51420", :nombre => "Venta al por mayor de metales y minerales metaliferos"
Clasificacion.create :codigo => "51431", :nombre => "Venta al por mayor de aberturas"
Clasificacion.create :codigo => "51432", :nombre => "Venta al por mayor de productos de madera excepto muebles"
Clasificacion.create :codigo => "51433", :nombre => "Venta al por mayor de articulos de ferreteria"
Clasificacion.create :codigo => "51434", :nombre => "Venta al por mayor de pinturas y productos conexos"
Clasificacion.create :codigo => "51435", :nombre => "Venta al por mayor de cristales y espejos"
Clasificacion.create :codigo => "51439", :nombre => "Venta al por mayor de articulos para la construccion n.c.p."
Clasificacion.create :codigo => "51491", :nombre => "Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos textiles"
Clasificacion.create :codigo => "51492", :nombre => "Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos de papel y carton"
Clasificacion.create :codigo => "51493", :nombre => "Venta al por mayor de productos intermedios, desperdicios y desechos de vidrio, de pl stico, de caucho y goma, y quimicos"
Clasificacion.create :codigo => "51494", :nombre => "Venta al por mayor de productos intermedios n.c.p., desperdicios y desechos met licos"
Clasificacion.create :codigo => "51499", :nombre => "Venta al por mayor de productos intermedios, desperdicios y desechos n.c.p."
Clasificacion.create :codigo => "51511", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso en los sectores agropecuario, jardineria, silvicultura, pesca y caza"
Clasificacion.create :codigo => "51512", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso en la elaboracion de alimentos, bebidas y tabaco"
Clasificacion.create :codigo => "51513", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso en la fabricacion de textiles, prendas y accesorios de vestir, calzado, articulos de cuero y marroquineria"
Clasificacion.create :codigo => "51514", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso en imprentas, artes gr ficas y actividades"
Clasificacion.create :codigo => "51515", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso m‚dico y param‚dico"
Clasificacion.create :codigo => "51516", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso en la industria del pl stico y el caucho"
Clasificacion.create :codigo => "51519", :nombre => "Venta al por mayor de m quinas, equipos e implementos de uso especial n.c.p."
Clasificacion.create :codigo => "51520", :nombre => "Venta al por mayor de m quinas-herramienta de uso general"
Clasificacion.create :codigo => "51530", :nombre => "Venta al por mayor de vehiculos, equipos y m quinas para el transporte ferroviario, a‚reo y de navegacion"
Clasificacion.create :codigo => "51541", :nombre => "Venta al por mayor de muebles e instalaciones para oficinas"
Clasificacion.create :codigo => "51542", :nombre => "Venta al por mayor de muebles e instalaciones para la industria, el comercio y los servicios n.c.p."
Clasificacion.create :codigo => "51591", :nombre => "Venta al por mayor de equipo profesional y cientifico e instrumentos de medida y de control n.c.p."
Clasificacion.create :codigo => "51592", :nombre => "Venta al por mayor de equipos inform ticos y m quinas electronicas de escribir y calcular ;Venta al por mayor de m quinas y equipos de comunicciones, control y seguridad"
Clasificacion.create :codigo => "51599", :nombre => "Venta al por mayor de m quinas, equipo y materiales conexos n.c.p."
Clasificacion.create :codigo => "51900", :nombre => "Venta al por mayor de mercancias n.c.p."
Clasificacion.create :codigo => "52111", :nombre => "Venta al por menor en hipermercados con predominio de productos alimenticios y bebidas"
Clasificacion.create :codigo => "52112", :nombre => "Venta al por menor en supermercados con predominio productos de alimenticios y bebidas"
Clasificacion.create :codigo => "52113", :nombre => "Venta al por menor en minimercados con predominio de productos alimenticios y bebidas"
Clasificacion.create :codigo => "52119", :nombre => "Venta al por menor en kioscos, polirrubros y comercios no especializados n.c.p."
Clasificacion.create :codigo => "52120", :nombre => "Venta al por menor excepto la especializada, sin predominio de productos alimenticios y bebidas"
Clasificacion.create :codigo => "52211", :nombre => "Venta al por menor principalmente de fiambres, quesos y productos l cteos"
Clasificacion.create :codigo => "52212", :nombre => "Venta al por menor de productos de almac‚n y diet‚tica"
Clasificacion.create :codigo => "52221", :nombre => "Venta al por menor de carnes rojas, menudencias y chacinados frescos"
Clasificacion.create :codigo => "52222", :nombre => "Venta al por menor de huevos, carne de aves y productos de granja y de la caza n.c.p."
Clasificacion.create :codigo => "52230", :nombre => "Venta al por menor de frutas, legumbres y hortalizas frescas"
Clasificacion.create :codigo => "52241", :nombre => "Venta al por menor de pan y productos de panaderia"
Clasificacion.create :codigo => "52242", :nombre => "Venta al por menor de bombones, golosinas y dem s productos de confiteria"
Clasificacion.create :codigo => "52250", :nombre => "Venta al por menor de bebidas"
Clasificacion.create :codigo => "52291", :nombre => "Venta al por menor de pescados y productos de la pesca"
Clasificacion.create :codigo => "52299", :nombre => "Venta al por menor de productos alimenticios n.c.p. y tabaco, en comercios especializados"
Clasificacion.create :codigo => "52311", :nombre => "Venta al por menor de productos farmac‚uticos y de herboristeria"
Clasificacion.create :codigo => "52312", :nombre => "Venta al por menor de productos cosm‚ticos, de tocador y de perfumeria"
Clasificacion.create :codigo => "52313", :nombre => "Venta al por menor de instrumental m‚dico y odontologico y articulos ortop‚dicos"
Clasificacion.create :codigo => "52321", :nombre => "Venta al por menor de hilados, tejidos y articulos de merceria"
Clasificacion.create :codigo => "52322", :nombre => "Venta al por menor de confecciones para el hogar"
Clasificacion.create :codigo => "52329", :nombre => "Venta al por menor de articulos textiles n.c.p. excepto prendas de vestir"
Clasificacion.create :codigo => "52331", :nombre => "Venta al por menor de ropa interior, medias, prendas para dormir y para la playa"
Clasificacion.create :codigo => "52332", :nombre => "Venta al por menor de indumentaria de trabajo, uniformes y guardapolvos"
Clasificacion.create :codigo => "52333", :nombre => "Venta al por menor de indumentaria para beb‚s y ninos"
Clasificacion.create :codigo => "52339", :nombre => "Venta al por menor de prendas y accesorios de vestir n.c.p. excepto calzado, articulos de marroquineria, paraguas y similares"
Clasificacion.create :codigo => "52341", :nombre => "Venta al por menor de articulos regionales y de talabarteria"
Clasificacion.create :codigo => "52342", :nombre => "Venta al por menor de calzado excepto el ortop‚dico"
Clasificacion.create :codigo => "52349", :nombre => "Venta al por menor de articulos de marroquineria, paraguas y similares n.c.p."
Clasificacion.create :codigo => "52351", :nombre => "Venta al por menor de muebles excepto para la oficina, la industria, el comercio y los servicios; articulos de mimbre y corcho"
Clasificacion.create :codigo => "52352", :nombre => "Venta al por menor de colchones y somieres"
Clasificacion.create :codigo => "52353", :nombre => "Venta al por menor de articulos de iluminacion"
Clasificacion.create :codigo => "52354", :nombre => "Venta al por menor de articulos de bazar y menaje"
Clasificacion.create :codigo => "52355", :nombre => "Venta al por menor de artefactos para el hogar, el‚ctricos, a gas, a kerosene u otros combustibles"
Clasificacion.create :codigo => "52356", :nombre => "Venta al por menor de instrumentos musicales, equipos de sonido, casetes de audio y video, discos de audio y video"
Clasificacion.create :codigo => "52359", :nombre => "Venta al por menor de articulos para el hogar n.c.p."
Clasificacion.create :codigo => "52361", :nombre => "Venta al por menor de aberturas"
Clasificacion.create :codigo => "52362", :nombre => "Venta al por menor de maderas y articulos de madera y corcho excepto muebles"
Clasificacion.create :codigo => "52363", :nombre => "Venta al por menor de articulos de ferreteria"
Clasificacion.create :codigo => "52364", :nombre => "Venta al por menor de pinturas y productos conexos"
Clasificacion.create :codigo => "52365", :nombre => "Venta al por menor de articulos para plomeria e instalacion de gas"
Clasificacion.create :codigo => "52366", :nombre => "Venta al por menor de cristales, espejos, mamparas y cerramientos"
Clasificacion.create :codigo => "52367", :nombre => "Venta al por menor de papeles para pared, revestimientos para pisos y articulos similares para la decoracion"
Clasificacion.create :codigo => "52369", :nombre => "Venta al por menor de materiales de construccion n.c.p."
Clasificacion.create :codigo => "52371", :nombre => "Venta al por menor de articulos de optica y fotografia"
Clasificacion.create :codigo => "52372", :nombre => "Venta al por menor de articulos de relojeria, joyeria y fantasia"
Clasificacion.create :codigo => "52381", :nombre => "Venta al por menor de libros y publicaciones"
Clasificacion.create :codigo => "52382", :nombre => "Venta al por menor de diarios y revistas"
Clasificacion.create :codigo => "52383", :nombre => "Venta al por menor de papel, carton, materiales de embalaje y articulos de libreria"
Clasificacion.create :codigo => "52391", :nombre => "Venta al por menor de flores, plantas, semillas, abonos, fertilizantes y otros productos de vivero"
Clasificacion.create :codigo => "52392", :nombre => "Venta al por menor de materiales y productos de limpieza"
Clasificacion.create :codigo => "52393", :nombre => "Venta al por menor de juguetes y articulos de cotillon"
Clasificacion.create :codigo => "52394", :nombre => "Venta al por menor de articulos de deportes y esparcimiento"
Clasificacion.create :codigo => "52395", :nombre => "Venta al por menor de m quinas y equipos para oficina y sus componentes y repuestos"
Clasificacion.create :codigo => "52396", :nombre => "Venta al por menor de fuel oil, gas en garrafas, carbon y lena"
Clasificacion.create :codigo => "52397", :nombre => "Venta al por menor de productos veterinarios y animales dom‚sticos"
Clasificacion.create :codigo => "52399", :nombre => "Venta al por menor de articulos de coleccion, obras de arte, y articulos nuevos n.c.p."
Clasificacion.create :codigo => "52410", :nombre => "Venta al por menor de muebles usados"
Clasificacion.create :codigo => "52420", :nombre => "Venta al por menor de libros, revistas y similares usados"
Clasificacion.create :codigo => "52491", :nombre => "Venta al por menor de antigedades"
Clasificacion.create :codigo => "52499", :nombre => "Venta al por menor de articulos usados n.c.p. excluidos automotores y motocicletas"
Clasificacion.create :codigo => "52510", :nombre => "Venta al por menor por correo, television, internet y otros medios de comunicacion"
Clasificacion.create :codigo => "52520", :nombre => "Venta al por menor en puestos moviles"
Clasificacion.create :codigo => "52590", :nombre => "Venta al por menor no realizada en establecimientos n.c.p."
Clasificacion.create :codigo => "52610", :nombre => "Reparacion de calzado y articulos de marroquineria"
Clasificacion.create :codigo => "52620", :nombre => "Reparacion de articulos el‚ctricos de uso dom‚stico"
Clasificacion.create :codigo => "52690", :nombre => "Reparacion de efectos personales y enseres dom‚sticos n.c.p."
Clasificacion.create :codigo => "55110", :nombre => "Servicios de alojamiento en camping"
Clasificacion.create :codigo => "55121", :nombre => "Servicios de alojamiento por hora"
Clasificacion.create :codigo => "55122", :nombre => "Servicios de alojamiento en hoteles, pensiones y otras residencias de alojamiento temporal, excepto por hora"
Clasificacion.create :codigo => "55211", :nombre => "Servicios de expendio de comidas y bebidas en restaurantes, bares y otros establecimientos con servicio de mesa y/o en mostrador excepto en heladerias"
Clasificacion.create :codigo => "55212", :nombre => "Servicios de expendio de helados"
Clasificacion.create :codigo => "55221", :nombre => "Provision de comidas preparadas para empresas"
Clasificacion.create :codigo => "55229", :nombre => "Preparacion y venta de comidas para llevar n.c.p."
Clasificacion.create :codigo => "60110", :nombre => "Servicio de transporte ferroviario de cargas"
Clasificacion.create :codigo => "60121", :nombre => "Servicio de transporte ferroviario urbano y suburbano de pasajeros"
Clasificacion.create :codigo => "60122", :nombre => "Servicio de transporte ferroviario interurbano de pasajeros"
Clasificacion.create :codigo => "60211", :nombre => "Servicios de mudanza"
Clasificacion.create :codigo => "60212", :nombre => "Servicios de transporte de mercaderias a granel, incluido el transporte por camion cisterna"
Clasificacion.create :codigo => "60213", :nombre => "Servicios de transporte de animales"
Clasificacion.create :codigo => "60218", :nombre => "Servicio de transporte urbano de carga n.c.p."
Clasificacion.create :codigo => "60219", :nombre => "Transporte automotor de cargas n.c.p."
Clasificacion.create :codigo => "60221", :nombre => "Servicio de transporte automotor urbano regular de pasajeros"
Clasificacion.create :codigo => "60222", :nombre => "Servicio de transporte automotor de pasajeros mediante taxis y remises; alquiler de autos con chofer"
Clasificacion.create :codigo => "60223", :nombre => "Servicio de transporte escolar"
Clasificacion.create :codigo => "60224", :nombre => "Servicio de transporte automotor urbano de oferta libre de pasajeros excepto mediante taxis y remises, alquiler de autos con chofer y transporte escolar"
Clasificacion.create :codigo => "60225", :nombre => "Servicio de transporte automotor interurbano de pasajeros"
Clasificacion.create :codigo => "60226", :nombre => "Servicio de transporte automotor de pasajeros para el turismo"
Clasificacion.create :codigo => "60229", :nombre => "Servicio de transporte automotor de pasajeros n.c.p."
Clasificacion.create :codigo => "60310", :nombre => "Servicio de transporte por oleoductos y poliductos"
Clasificacion.create :codigo => "60320", :nombre => "Servicio de transporte por gasoductos"
Clasificacion.create :codigo => "61110", :nombre => "Servicio de transporte maritimo de carga"
Clasificacion.create :codigo => "61120", :nombre => "Servicio de transporte maritimo de pasajeros"
Clasificacion.create :codigo => "61210", :nombre => "Servicio de transporte fluvial de cargas"
Clasificacion.create :codigo => "61220", :nombre => "Servicio de transporte fluvial de pasajeros"
Clasificacion.create :codigo => "62100", :nombre => "Servicio de transporte a‚reo de cargas"
Clasificacion.create :codigo => "62200", :nombre => "Servicio de transporte a‚reo de pasajeros"
Clasificacion.create :codigo => "63100", :nombre => "Servicios de manipulacion de carga"
Clasificacion.create :codigo => "63200", :nombre => "Servicios de almacenamiento y deposito"
Clasificacion.create :codigo => "63311", :nombre => "Servicios explotacion de infraestructura; peajes y otros derechos"
Clasificacion.create :codigo => "63312", :nombre => "Servicios prestados por playas de estacionamiento y garajes"
Clasificacion.create :codigo => "63319", :nombre => "Servicios complementarios para el transporte terrestre n.c.p."
Clasificacion.create :codigo => "63321", :nombre => "Servicios de explotacion de infraestructura; derechos de puerto"
Clasificacion.create :codigo => "63322", :nombre => "Servicios de guarderias n uticas"
Clasificacion.create :codigo => "63323", :nombre => "Servicios para la navegacion"
Clasificacion.create :codigo => "63329", :nombre => "Servicios complementarios para el transporte por agua n.c.p."
Clasificacion.create :codigo => "63331", :nombre => "Servicios de hangares, estacionamiento y remolque de aeronaves"
Clasificacion.create :codigo => "63332", :nombre => "Servicios para la aeronavegacion"
Clasificacion.create :codigo => "63339", :nombre => "Servicios complementarios para el transporte a‚reo n.c.p."
Clasificacion.create :codigo => "63410", :nombre => "Servicios mayoristas de agencias de viajes"
Clasificacion.create :codigo => "63420", :nombre => "Servicios minoristas de agencias de viajes"
Clasificacion.create :codigo => "63430", :nombre => "Servicios complementarios de apoyo turistico"
Clasificacion.create :codigo => "63500", :nombre => "Servicios de gestion y logistica para el transporte de mercaderias"
Clasificacion.create :codigo => "64100", :nombre => "Servicios de correos"
Clasificacion.create :codigo => "64201", :nombre => "Servicios de transmision de radio y television"
Clasificacion.create :codigo => "64202", :nombre => "Servicios de comunicacion por medio de tel‚fono, tel‚grafo y telex"
Clasificacion.create :codigo => "64209", :nombre => "Servicios de transmision n.c.p. de sonido, im genes, datos u otra informacion"
Clasificacion.create :codigo => "65110", :nombre => "Servicios de la banca central"
Clasificacion.create :codigo => "65211", :nombre => "Servicios de la banca mayorista"
Clasificacion.create :codigo => "65212", :nombre => "Servicios de la banca de inversion"
Clasificacion.create :codigo => "65213", :nombre => "Servicios de la banca minorista"
Clasificacion.create :codigo => "65220", :nombre => "Servicios de las entidades financieras no bancarias"
Clasificacion.create :codigo => "65981", :nombre => "Actividades de cr‚dito para financiar otras actividades economicas"
Clasificacion.create :codigo => "65989", :nombre => "Servicios de cr‚dito n.c.p."
Clasificacion.create :codigo => "65991", :nombre => "Servicios de agentes de mercado abierto puros"
Clasificacion.create :codigo => "65992", :nombre => "Servicios de entidades de tarjeta de compra y/o cr‚dito"
Clasificacion.create :codigo => "65999", :nombre => "Servicios de financiacion y actividades financieras n.c.p."
Clasificacion.create :codigo => "66111", :nombre => "Servicios de seguros de salud"
Clasificacion.create :codigo => "66112", :nombre => "Servicios de seguros de vida"
Clasificacion.create :codigo => "66113", :nombre => "Servicio de seguros a las personas excepto los de salud y de vida"
Clasificacion.create :codigo => "66121", :nombre => "Servicios de aseguradoras de riesgo de trabajo (ART)"
Clasificacion.create :codigo => "66122", :nombre => "Servicios de seguros patrimoniales excepto los de las aseguradoras de riesgo de trabajo"
Clasificacion.create :codigo => "66130", :nombre => "Reaseguros"
Clasificacion.create :codigo => "66200", :nombre => "Administracion de fondos de jubilaciones y pensiones (AFJP)"
Clasificacion.create :codigo => "67111", :nombre => "Servicios de mercados y cajas de valores"
Clasificacion.create :codigo => "67112", :nombre => "Servicios de mercados a t‚rmino"
Clasificacion.create :codigo => "67113", :nombre => "Servicios de bolsas de Comercio"
Clasificacion.create :codigo => "67120", :nombre => "Servicios burs tiles de mediacion o por cuenta de terceros"
Clasificacion.create :codigo => "67191", :nombre => "Servicios de casas y agencias de cambio"
Clasificacion.create :codigo => "67192", :nombre => "Servicios de sociedades calificadoras de riesgos"
Clasificacion.create :codigo => "67199", :nombre => "Servicios auxiliares a la intermediacion financiera n.c.p., excepto a los servicios de seguros y de administracion de fondos de jubilaciones y pensiones"
Clasificacion.create :codigo => "67211", :nombre => "Servicios de productores y asesores de seguros"
Clasificacion.create :codigo => "67219", :nombre => "Servicios auxiliares a los servicios de seguros n.c.p"
Clasificacion.create :codigo => "67220", :nombre => "Servicios auxiliares a la administracion de fondos de jubilaciones y pensiones"
Clasificacion.create :codigo => "70101", :nombre => "Servicios de alquiler y explotacion de inmuebles para fiestas, convenciones y otros eventos similares"
Clasificacion.create :codigo => "70109", :nombre => "Servicios inmobiliarios realizados por cuenta propia, con bienes propios o arrendados n.c.p."
Clasificacion.create :codigo => "70200", :nombre => "Servicios inmobiliarios realizados a cambio de una retribucion o por contrata"
Clasificacion.create :codigo => "71110", :nombre => "Alquiler de equipo de transporte para via terrestre, sin operarios"
Clasificacion.create :codigo => "71120", :nombre => "Alquiler de equipo de transporte para via acu tica, sin operarios ni tripulacion"
Clasificacion.create :codigo => "71130", :nombre => "Alquiler de equipo de transporte para via a‚rea, sin operarios ni tripulacion"
Clasificacion.create :codigo => "71210", :nombre => "Alquiler de maquinaria y equipo agropecuario, sin operarios"
Clasificacion.create :codigo => "71220", :nombre => "Alquiler de maquinaria y equipo de construccion e ingenieria civil, sin operarios"
Clasificacion.create :codigo => "71230", :nombre => "Alquiler de maquinaria y equipo de oficina, incluso computadoras"
Clasificacion.create :codigo => "71290", :nombre => "Alquiler de maquinaria y equipo n.c.p., sin personal"
Clasificacion.create :codigo => "71300", :nombre => "Alquiler de efectos personales y enseres dom‚sticos n.c.p."
Clasificacion.create :codigo => "72100", :nombre => "Servicios de consultores en equipo de inform tica"
Clasificacion.create :codigo => "72200", :nombre => "Servicios de consultores en inform tica y suministros de programas de inform tica"
Clasificacion.create :codigo => "72300", :nombre => "Procesamiento de datos"
Clasificacion.create :codigo => "72400", :nombre => "Servicios relacionados con bases de datos"
Clasificacion.create :codigo => "72500", :nombre => "Mantenimiento y reparacion de maquinaria de oficina, contabilidad e inform tica"
Clasificacion.create :codigo => "72900", :nombre => "Actividades de inform tica n.c.p."
Clasificacion.create :codigo => "73110", :nombre => "Investigacion y desarrollo experimental en el campo de la ingenieria y la tecnologia"
Clasificacion.create :codigo => "73120", :nombre => "Investigacion y desarrollo experimental en el campo de las ciencias m‚dicas"
Clasificacion.create :codigo => "73130", :nombre => "Investigacion y desarrollo experimental en el campo de las ciencias agropecuarias"
Clasificacion.create :codigo => "73190", :nombre => "Investigacion y desarrollo experimental en el campo de las ciencias exactas y naturales n.c.p."
Clasificacion.create :codigo => "73210", :nombre => "Investigacion y desarrollo experimental en el campo de las ciencias sociales"
Clasificacion.create :codigo => "73220", :nombre => "Investigacion y desarrollo experimental en el campo de las ciencias humanas"
Clasificacion.create :codigo => "74110", :nombre => "Servicios juridicos"
Clasificacion.create :codigo => "74120", :nombre => "Servicios de contabilidad y teneduria de libros, auditoria y asesoria fiscal"
Clasificacion.create :codigo => "74130", :nombre => "Estudio de mercado, realizacion de encuestas de opinion p£blica"
Clasificacion.create :codigo => "74140", :nombre => "Servicios de asesoramiento, direccion y gestion empresarial"
Clasificacion.create :codigo => "74210", :nombre => "Servicios de arquitectura e ingenieria y servicios conexos de asesoramiento t‚cnico"
Clasificacion.create :codigo => "74220", :nombre => "Ensayos y an lisis t‚cnicos"
Clasificacion.create :codigo => "74300", :nombre => "Servicios de publicidad"
Clasificacion.create :codigo => "74910", :nombre => "Obtencion y dotacion de personal"
Clasificacion.create :codigo => "74921", :nombre => "Servicios de transporte de caudales y objetos de valor"
Clasificacion.create :codigo => "74929", :nombre => "Servicios de investigacion y seguridad n.c.p."
Clasificacion.create :codigo => "74930", :nombre => "Servicios de limpieza de edificios"
Clasificacion.create :codigo => "74940", :nombre => "Servicios de fotografia"
Clasificacion.create :codigo => "74950", :nombre => "Servicios de envase y empaque"
Clasificacion.create :codigo => "74960", :nombre => "Servicios de impresion heliogr fica, fotocopia y otras formas de reproducciones"
Clasificacion.create :codigo => "74990", :nombre => "Servicios empresariales n.c.p."
Clasificacion.create :codigo => "75110", :nombre => "Servicios generales de la Administracion P£blica"
Clasificacion.create :codigo => "75120", :nombre => "Servicios para la regulacion de las actividades sanitarias, educativas, culturales, y restantes servicios sociales, excepto seguridad social obligatoria"
Clasificacion.create :codigo => "75130", :nombre => "Servicios para la regulacion de la actividad economica"
Clasificacion.create :codigo => "75190", :nombre => "Servicios auxiliares para los servicios generales de la Administracion P£blica"
Clasificacion.create :codigo => "75210", :nombre => "Servicios de Asuntos exteriores"
Clasificacion.create :codigo => "75220", :nombre => "Servicios de Defensa"
Clasificacion.create :codigo => "75230", :nombre => "Servicios de Justicia"
Clasificacion.create :codigo => "75240", :nombre => "Servicios para el orden p£blico y la seguridad"
Clasificacion.create :codigo => "75250", :nombre => "Servicios de proteccion civil"
Clasificacion.create :codigo => "75300", :nombre => "Servicios de la seguridad social obligatoria"
Clasificacion.create :codigo => "80100", :nombre => "Ensenanza inicial y primaria"
Clasificacion.create :codigo => "80210", :nombre => "Ensenanza secundaria de formacion general"
Clasificacion.create :codigo => "80220", :nombre => "Ensenanza secundaria de formacion t‚cnica y profesional"
Clasificacion.create :codigo => "80310", :nombre => "Ensenanza terciaria"
Clasificacion.create :codigo => "80320", :nombre => "Ensenanza universitaria excepto formacion de postgrados"
Clasificacion.create :codigo => "80330", :nombre => "Formacion de posgrado"
Clasificacion.create :codigo => "80900", :nombre => "Ensenanza para adultos y servicios de ensenanza n.c.p."
Clasificacion.create :codigo => "85111", :nombre => "Servicios de internacion"
Clasificacion.create :codigo => "85112", :nombre => "Servicios de hospital de dia"
Clasificacion.create :codigo => "85119", :nombre => "Servicios hospitalarios n.c.p."
Clasificacion.create :codigo => "85121", :nombre => "Servicios de atencion ambulatoria"
Clasificacion.create :codigo => "85122", :nombre => "Servicios de atencion domiciliaria programada"
Clasificacion.create :codigo => "85130", :nombre => "Servicios odontologicos"
Clasificacion.create :codigo => "85140", :nombre => "Servicios de diagnostico"
Clasificacion.create :codigo => "85150", :nombre => "Servicios de tratamiento"
Clasificacion.create :codigo => "85160", :nombre => "Servicios de emergencias y traslados"
Clasificacion.create :codigo => "85190", :nombre => "Servicios relacionados con la salud humana n.c.p."
Clasificacion.create :codigo => "85200", :nombre => "Servicios veterinarios"
Clasificacion.create :codigo => "85311", :nombre => "Servicios de atencion a ancianos con alojamiento"
Clasificacion.create :codigo => "85312", :nombre => "Servicios de atencion a personas minusv lidas con alojamiento"
Clasificacion.create :codigo => "85313", :nombre => "Servicios de atencion a menores con alojamiento"
Clasificacion.create :codigo => "85314", :nombre => "Servicios de atencion a mujeres con alojamiento"
Clasificacion.create :codigo => "85319", :nombre => "Servicios sociales con alojamiento n.c.p."
Clasificacion.create :codigo => "85320", :nombre => "Servicios sociales sin alojamiento"
Clasificacion.create :codigo => "90001", :nombre => "Recoleccion, reduccion y eliminacion de desperdicios"
Clasificacion.create :codigo => "90002", :nombre => "Servicios de depuracion de aguas residuales, alcantarillado y cloacas"
Clasificacion.create :codigo => "90009", :nombre => "Servicios de saneamiento p£blico n.c.p."
Clasificacion.create :codigo => "91110", :nombre => "Servicios de federaciones de asociaciones, c maras, gremios y organizaciones similares"
Clasificacion.create :codigo => "91120", :nombre => "Servicios de asociaciones de especialistas en disciplinas cientificas, pr cticas profesionales y esferas t‚cnicas"
Clasificacion.create :codigo => "91200", :nombre => "Servicios de sindicatos"
Clasificacion.create :codigo => "91910", :nombre => "Servicios de organizaciones religiosas"
Clasificacion.create :codigo => "91920", :nombre => "Servicios de organizaciones politicas"
Clasificacion.create :codigo => "91990", :nombre => "Servicios de asociaciones n.c.p."
Clasificacion.create :codigo => "92111", :nombre => "Produccion de filmes y videocintas"
Clasificacion.create :codigo => "92112", :nombre => "Distribucion de filmes y videocintas"
Clasificacion.create :codigo => "92120", :nombre => "Exhibicion de filmes y videocintas"
Clasificacion.create :codigo => "92130", :nombre => "Servicios de radio y television"
Clasificacion.create :codigo => "92141", :nombre => "Produccion de espect culos teatrales y musicales"
Clasificacion.create :codigo => "92142", :nombre => "Composicion y representacion de obras teatrales, musicales y artisticas"
Clasificacion.create :codigo => "92143", :nombre => "Servicios conexos a la produccion de espect culos teatrales y musicales"
Clasificacion.create :codigo => "92191", :nombre => "Servicios de salones de baile, discotecas y similares"
Clasificacion.create :codigo => "92199", :nombre => "Servicios de espect culos artisticos y de diversion n.c.p."
Clasificacion.create :codigo => "92200", :nombre => "Servicios de agencias de noticias y servicios de informacion"
Clasificacion.create :codigo => "92310", :nombre => "Servicios de bibliotecas y archivos"
Clasificacion.create :codigo => "92320", :nombre => "Servicios de museos y preservacion de lugares y edificios historicos"
Clasificacion.create :codigo => "92330", :nombre => "Servicios de jardines bot nicos, zoologicos y de parques nacionales"
Clasificacion.create :codigo => "92411", :nombre => "Servicios de organizacion, direccion y gestion de pr cticas deportivas y explotacion de las instalaciones"
Clasificacion.create :codigo => "92412", :nombre => "Promocion y produccion de espect culos deportivos"
Clasificacion.create :codigo => "92413", :nombre => "Servicios prestados por profesionales y t‚cnicos, para la realizacion de pr cticas deportivas"
Clasificacion.create :codigo => "92491", :nombre => "Servicios de esparcimiento relacionadas con juegos de azar y apuestas"
Clasificacion.create :codigo => "92492", :nombre => "Servicios de salones de juegos"
Clasificacion.create :codigo => "92499", :nombre => "Servicios de entretenimiento n.c.p."
Clasificacion.create :codigo => "93010", :nombre => "Lavado y limpieza de articulos de tela, cuero y/o de piel, incluso la limpieza en seco"
Clasificacion.create :codigo => "93020", :nombre => "Servicios de peluqueria y tratamientos de belleza"
Clasificacion.create :codigo => "93030", :nombre => "Pompas fúnebres y servicios conexos"
Clasificacion.create :codigo => "93091", :nombre => "Servicios para el mantenimiento fisico-corporal"
Clasificacion.create :codigo => "93099", :nombre => "Servicios n.c.p."
Clasificacion.create :codigo => "95000", :nombre => "Servicios de hogares privados que contratan servicio dom‚stico"
Clasificacion.create :codigo => "99000", :nombre => "Servicios de organizaciones y organos extraterritoriales"
